name: Test
on: 
  push: 
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup Node.js
        uses: actions/setup-node@v6
        with:   
          node-version: 26
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with: 
          bun-version: 1.3.14
      - name: install deps
        run: bun ci
      - name: build
        run: bun run trick-tsd && bun run build
      - name: run test
        run: bun run test
      - name: Custom benchmark with BunJS
        run: bun tests/benchmark.ts
      - name: Custom benchmark with NodeJS
        run: bun x tsx tests/benchmark.ts
      - name: Modified fast-json-stringify benchmark with Bun
        run: bun tests/fast-json-stringify-benchmark.ts
      - name: Modified fast-json-stringify benchmark with NodeJS
        run: bun x tsx tests/fast-json-stringify-benchmark.ts
